/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IMultiTokenRewardRecipientInterface extends ethers.utils.Interface {
  functions: {
    "notifyTokenAmount(address,tuple)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "notifyTokenAmount",
    values: [string, { d: BigNumberish }]
  ): string;

  decodeFunctionResult(
    functionFragment: "notifyTokenAmount",
    data: BytesLike
  ): Result;

  events: {};
}

export class IMultiTokenRewardRecipient extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IMultiTokenRewardRecipientInterface;

  functions: {
    notifyTokenAmount(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "notifyTokenAmount(address,tuple)"(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  notifyTokenAmount(
    _token: string,
    _amount: { d: BigNumberish },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "notifyTokenAmount(address,tuple)"(
    _token: string,
    _amount: { d: BigNumberish },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    notifyTokenAmount(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;

    "notifyTokenAmount(address,tuple)"(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    notifyTokenAmount(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "notifyTokenAmount(address,tuple)"(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    notifyTokenAmount(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "notifyTokenAmount(address,tuple)"(
      _token: string,
      _amount: { d: BigNumberish },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
