/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPerpToken } from "../IPerpToken";

export class IPerpToken__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPerpToken {
    return new Contract(address, _abi, signerOrProvider) as IPerpToken;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
